name: Build Skent

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java environement
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Build Skent
        run: ./gradlew build

      - name: Upload nightly build
        uses: actions/upload-artifact@v4
        with:
          name: Skent
          path: build/libs/Skent.jar
