name: Build Skent

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          architecture: x64

      - name: Build Skent
        run: ./gradlew clean build

      - name: Upload nightly build
        uses: actions/upload-artifact@v2
        with:
          name: Skent
          path: build/libs/Skent.jar
